// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAONVIZlb8wcdGBQZ-zK-ZULlBLFXpq6cc',
    appId: '1:804538035628:web:88bfd3b4a1667c0bbf5e09',
    messagingSenderId: '804538035628',
    projectId: 'travelcompanionapp-c8ed7',
    authDomain: 'travelcompanionapp-c8ed7.firebaseapp.com',
    storageBucket: 'travelcompanionapp-c8ed7.firebasestorage.app',
    measurementId: 'G-D2S2QK7LVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsZmoIHVyTTrS56RfUy5Etb3SFjeqVKOk',
    appId: '1:804538035628:android:543515d86f4a4de3bf5e09',
    messagingSenderId: '804538035628',
    projectId: 'travelcompanionapp-c8ed7',
    storageBucket: 'travelcompanionapp-c8ed7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOwAsdO5UxhqvmjOLYqEaHpQT4f5i0eFg',
    appId: '1:804538035628:ios:374a907de1c21a07bf5e09',
    messagingSenderId: '804538035628',
    projectId: 'travelcompanionapp-c8ed7',
    storageBucket: 'travelcompanionapp-c8ed7.firebasestorage.app',
    iosBundleId: 'com.example.travelcompanionfinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOwAsdO5UxhqvmjOLYqEaHpQT4f5i0eFg',
    appId: '1:804538035628:ios:374a907de1c21a07bf5e09',
    messagingSenderId: '804538035628',
    projectId: 'travelcompanionapp-c8ed7',
    storageBucket: 'travelcompanionapp-c8ed7.firebasestorage.app',
    iosBundleId: 'com.example.travelcompanionfinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAONVIZlb8wcdGBQZ-zK-ZULlBLFXpq6cc',
    appId: '1:804538035628:web:383b2f722c4e1ce9bf5e09',
    messagingSenderId: '804538035628',
    projectId: 'travelcompanionapp-c8ed7',
    authDomain: 'travelcompanionapp-c8ed7.firebaseapp.com',
    storageBucket: 'travelcompanionapp-c8ed7.firebasestorage.app',
    measurementId: 'G-KF3R96CFWC',
  );
}
